### ISSUE TITLE
Add `defaults` to the module (Yoshi flow editor packages)

### ISSUE THREAD

**Issue by sidoruk-sv** [wix-incubator/tpa-style-webpack-plugin#28]
For now, for the sake of https://github.com/wix-private/yoshi/issues/4709 we want to add new property `defaults` for cssConfig.

Due to the fact that standalone cssProcessor and bundle generation is located in `tpa-style-webpack-plugin` we would not need to change https://github.com/wix-private/thunderbolt/blob/master/packages/thunderbolt-becky/src/siteAssetsModules/helpers/ooiCssProcessor.ts

We have knowledge of that defaults on build time:
every default value is listed in component file `stylesParams.ts` as an example [ChallengesList component](https://github.com/wix-private/strategic-products/blob/master/achievements/web-client/challenges-web-ooi/src/components/ChallengesList/stylesParams.ts)

So need ability to parse and provide list of that defaults.

**Comment by ronnyrin** [comment]
sounds good
