### ISSUE TITLE
Handle `defaults` parameter inside `getProcessedCssWithConfig`  function

### ISSUE THREAD

**Issue by sidoruk-sv** [wix-incubator/tpa-style-webpack-plugin#29]
Should be done after #28 

For the sake of https://github.com/wix-private/yoshi/issues/4709

We try to provide optimization for Thunderbolt, so need to handle `processedCssConfig.defaults` inside `standalone.ts > getProcessedCssWithConfig` function.

where `defaults` is the result of #28.

**Comment by ronnyrin** [comment]
sounds good

**Comment by sidoruk-sv** [comment]
Would be implemented in private package
